// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90tz238ElArz2Ao90vTusfEEd7ufWnx4',
    appId: '1:184992033712:web:1f06050043eca6d3848475',
    messagingSenderId: '184992033712',
    projectId: 'testwebrtc-41ea6',
    authDomain: 'testwebrtc-41ea6.firebaseapp.com',
    storageBucket: 'testwebrtc-41ea6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAOR3M4Ln7AsY4_R4kn_zJkHyoqDhKMso',
    appId: '1:184992033712:android:952ce7da587fbeac848475',
    messagingSenderId: '184992033712',
    projectId: 'testwebrtc-41ea6',
    storageBucket: 'testwebrtc-41ea6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Iv07z6vWZZINmRib-eUyNF921t2RgWQ',
    appId: '1:184992033712:ios:bf0201c13c32b7bb848475',
    messagingSenderId: '184992033712',
    projectId: 'testwebrtc-41ea6',
    storageBucket: 'testwebrtc-41ea6.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );
}
